### ISSUE TITLE
cheerio.load() expects a string

### ISSUE THREAD

**Issue by cstoff6** [Batman110391/scrape-html-web#1]
Hi! I'm continuously getting this error with the way my code is structured and wondering if you can point me into the right direction.

Trying to use it in a component that will pull the img url from zillow, but even when I'm using your test case I'm getting this error.

```js
import { scrapeHtmlWeb } from "scrape-html-web";

export const getImageUrls = async (url) => {

    const options = {
        url: url,
        bypassCors: true,
        mainSelector:".blog-index",
        childrenSelector: [
        { key: "img", selector: "time", attr: "text" },

        ],
    };
    
    (async () => {
        const data = await scrapeHtmlWeb(options);
        console.log(data);
        // return data
    })();
}
```

```js
import { useEffect, useState } from "react";
import { getImageUrls } from "../hooks/getImageUrls";

const ZillowImage = (url) => {

    const [imgUrl,setImageUrl] = useState(null);

    useEffect(() => {
        getImageUrls(url)
        .then((data) => {
            setImageUrl(data)
    });

        },[])
    
    return (!imgUrl ? (
        <div>Loading...</div>
        ) : (
            <div>
            <img src={imgUrl[0].img}></img>
            </div>
        )

    )

}

export default ZillowImage;
```

Thanks in advance if you have any suggestions on how to overcome this error.

**Comment by Batman110391** [comment]
Hello,

Are you sure you pass the correct data in the options of the call you make to scrapeHtmlWeb ? I see that you are using data that most likely does not match the HTML you need: 

See for example: 
- ".blog-index"
- { key: "img", selector: "time", attr: "text" }

These are the parameters inherent in the example that work not the html that the example page returns.

You should inspect the html that returns the URL you call and pass the correct parameters according to the documentation
